// Code generated by "stringer -type=Alert -linecomment -output alert_generated.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlertInfo-0]
	_ = x[AlertSuccess-1]
	_ = x[AlertWarning-2]
	_ = x[AlertError-3]
}

const _Alert_name = "alert-infoalert-successalert-warningalert-error"

var _Alert_index = [...]uint8{0, 10, 23, 36, 47}

func (i Alert) String() string {
	if i < 0 || i >= Alert(len(_Alert_index)-1) {
		return "Alert(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Alert_name[_Alert_index[i]:_Alert_index[i+1]]
}
