// Code generated by "stringer -type=Alignment -linecomment -output alignment_generated.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlignEnd-0]
	_ = x[AlignTop-1]
	_ = x[AlignBottom-2]
	_ = x[AlignMiddle-3]
	_ = x[AlignLeft-4]
	_ = x[AlignRight-5]
}

const _Alignment_name = "AlignEndAlignTopAlignBottomAlignMiddleAlignLeftAlignRight"

var _Alignment_index = [...]uint8{0, 8, 16, 27, 38, 47, 57}

func (i Alignment) String() string {
	if i < 0 || i >= Alignment(len(_Alignment_index)-1) {
		return "Alignment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Alignment_name[_Alignment_index[i]:_Alignment_index[i+1]]
}
