// Code generated by "stringer -type=ProseGrayScale -linecomment -output article_generated.go"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Gray-0]
	_ = x[Slate-1]
	_ = x[Zinc-2]
	_ = x[Neutral-3]
	_ = x[Stone-4]
}

const _ProseGrayScale_name = "prose-grayprose-slateprose-zincprose-neutralprose-stone"

var _ProseGrayScale_index = [...]uint8{0, 10, 21, 31, 44, 55}

func (i ProseGrayScale) String() string {
	if i < 0 || i >= ProseGrayScale(len(_ProseGrayScale_index)-1) {
		return "ProseGrayScale(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProseGrayScale_name[_ProseGrayScale_index[i]:_ProseGrayScale_index[i+1]]
}
