// Code generated by "stringer -type=Color -linecomment -output color_generated.go"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorNeutral-0]
	_ = x[ColorNeutralContent-1]
	_ = x[ColorPrimary-2]
	_ = x[ColorPrimaryContent-3]
	_ = x[ColorSecondary-4]
	_ = x[ColorSecondaryContent-5]
	_ = x[ColorAccent-6]
	_ = x[ColorAccentContent-7]
	_ = x[ColorInfo-8]
	_ = x[ColorInfoContent-9]
	_ = x[ColorSuccess-10]
	_ = x[ColorSuccessContent-11]
	_ = x[ColorWarning-12]
	_ = x[ColorWarningContent-13]
	_ = x[ColorError-14]
	_ = x[ColorErrorContent-15]
	_ = x[ColorGhost-16]
}

const _Color_name = "bg-neutralbg-neutral-contentbg-primarybg-primary-contentbg-secondarybg-secondary-contentbg-accentbg-accent-contentbg-infobg-info-contentbg-successbg-success-contentbg-warningbg-warning-contentbg-errorbg-error-contentbg-ghost"

var _Color_index = [...]uint8{0, 10, 28, 38, 56, 68, 88, 97, 114, 121, 136, 146, 164, 174, 192, 200, 216, 224}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
