// Code generated by "stringer -type=DropDownOpen,DropDownStyle -linecomment -output dropdown_generated.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DropDownTop-0]
	_ = x[DropDownBottom-1]
	_ = x[DropDownLeft-2]
	_ = x[DropDownRight-3]
}

const _DropDownOpen_name = "dropdown-topdropdown-bottomdropdown-leftdropdown-right"

var _DropDownOpen_index = [...]uint8{0, 12, 27, 40, 54}

func (i DropDownOpen) String() string {
	if i < 0 || i >= DropDownOpen(len(_DropDownOpen_index)-1) {
		return "DropDownOpen(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DropDownOpen_name[_DropDownOpen_index[i]:_DropDownOpen_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DropDownButton-0]
	_ = x[DropDownCard-1]
	_ = x[DropDownCustom-2]
}

const _DropDownStyle_name = "DropDownButtonDropDownCardDropDownCustom"

var _DropDownStyle_index = [...]uint8{0, 14, 26, 40}

func (i DropDownStyle) String() string {
	if i < 0 || i >= DropDownStyle(len(_DropDownStyle_index)-1) {
		return "DropDownStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DropDownStyle_name[_DropDownStyle_index[i]:_DropDownStyle_index[i+1]]
}
