// Code generated by "stringer -type=HeaderSize -linecomment -output header_generated.go"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[H1-0]
	_ = x[H2-1]
	_ = x[H3-2]
	_ = x[H4-3]
	_ = x[H5-4]
	_ = x[H6-5]
}

const _HeaderSize_name = "h1h2h3h4h5h6"

var _HeaderSize_index = [...]uint8{0, 2, 4, 6, 8, 10, 12}

func (i HeaderSize) String() string {
	if i < 0 || i >= HeaderSize(len(_HeaderSize_index)-1) {
		return "HeaderSize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HeaderSize_name[_HeaderSize_index[i]:_HeaderSize_index[i+1]]
}
