// Code generated by "stringer -type=FAStyle -linecomment -output icon_generated.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Solid-0]
}

const _FAStyle_name = "fa-solid"

var _FAStyle_index = [...]uint8{0, 8}

func (i FAStyle) String() string {
	if i < 0 || i >= FAStyle(len(_FAStyle_index)-1) {
		return "FAStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FAStyle_name[_FAStyle_index[i]:_FAStyle_index[i+1]]
}
