// Code generated by "stringer -type=Layout -linecomment -output layout_generated.go"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VerticalLayout-0]
	_ = x[HorizontalLayout-1]
}

const _Layout_name = "verticalhorizontal"

var _Layout_index = [...]uint8{0, 8, 18}

func (i Layout) String() string {
	if i < 0 || i >= Layout(len(_Layout_index)-1) {
		return "Layout(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Layout_name[_Layout_index[i]:_Layout_index[i+1]]
}
