// Code generated by "stringer -type=Size -linecomment -output size_generated.go"; DO NOT EDIT.

package components

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MD-0]
	_ = x[XS-1]
	_ = x[SM-2]
	_ = x[LG-3]
}

const _Size_name = "mdxssmlg"

var _Size_index = [...]uint8{0, 2, 4, 6, 8}

func (i Size) String() string {
	if i < 0 || i >= Size(len(_Size_index)-1) {
		return "Size(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Size_name[_Size_index[i]:_Size_index[i+1]]
}
