// Code generated by "stringer -type=State -linecomment -output state.gen.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MinInvalid-0]
	_ = x[Info-1]
	_ = x[Success-2]
	_ = x[Warning-3]
	_ = x[Error-4]
	_ = x[MaxInvalid-5]
}

const _State_name = "MinInvalidinfosuccesswarningerrorMaxInvalid"

var _State_index = [...]uint8{0, 10, 14, 21, 28, 33, 43}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
