// Code generated by "stringer -type=Type -linecomment -output textinput_type_generated.go"; DO NOT EDIT.

package textinput

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeText-0]
	_ = x[TypePassword-1]
	_ = x[TypeEmail-2]
	_ = x[TypeURL-3]
}

const _Type_name = "textpasswordemailurl"

var _Type_index = [...]uint8{0, 4, 12, 17, 20}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
